ALTER TABLE ActualTotalLoad DROP FOREIGN KEY FKActualTota412327;
ALTER TABLE AggrGenerationPerType DROP FOREIGN KEY FKAggrGenera687323;
ALTER TABLE PhysicalFlows DROP FOREIGN KEY FKPhysicalFl871357;
ALTER TABLE PhysicalFlows DROP FOREIGN KEY FKPhysicalFl555898;
DROP TABLE IF EXISTS ActualTotalLoad;
DROP TABLE IF EXISTS AggrGenerationPerType;
DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS PhysicalFlows;
DROP TABLE IF EXISTS Subscriptions;
